<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
	    <meta name="author" content="Julio Viera">
	    <meta name="description" content="<?php echo $this->meta->getDescription()?>">
	    <meta name="keywords" content="<?php echo $this->meta->getKeywords() ?>">
	    <title><?php echo $this->meta->getTitle() ?></title>
		
					
		<link rel="stylesheet" type="text/css" href="/css/app.css">
	    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/img/favicon.ico">
    	
    </head>
    <body>	
    	<header id="cabecera">
			<?php echo $this->partial('sitio/partial/cabecera.phtml',  array("usuario" => $this->usuario)) ?>
    	</header>
		
        <section id="principal" class="centrado sombra1">
			<h2>Coso MVC 2021</h2>
        	<article id="contenido">
        		<?php echo $this->content; ?>
        	</article>
                    	
        </section>
        <footer id="pie" class="centrado">
			<aside class="links-pie">
				<ul>
					<li><a href="/publico/contacto/">Contacto</a></li>
				</ul>
			</aside>
		</footer>
              
<input type="hidden" id="csrf" value="<?php echo $this->csrf?>">
		        
<script type="text/javascript" src="/js/app.js" charset="utf-8"></script>
</body>
</html>
